# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a corrupted csv file!

## Objectives
You will be able to:
* Import data from csv files and Excel files
* Understand and explain key arguments for imports
* Save information to csv and Excel files
* Access data within a Pandas DataFrame (print() and .head())

##  Loading Files with Summary or Meta Data

Load either of the files Zipcode_Demos.csv or Zipcode_Demos.xlsx. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled 'Data'.

In [1]:
import pandas as pd
df = pd.read_csv('Data/Zipcode_Demos.csv')
df.head()

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,JURISDICTION NAME,10005.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,COUNT PARTICIPANTS,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,COUNT FEMALE,4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,PERCENT FEMALE,0.404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 47 columns):
0                     57 non-null int64
Average Statistics    56 non-null object
Unnamed: 2            57 non-null object
Unnamed: 3            11 non-null object
Unnamed: 4            11 non-null object
Unnamed: 5            11 non-null object
Unnamed: 6            11 non-null object
Unnamed: 7            11 non-null object
Unnamed: 8            11 non-null object
Unnamed: 9            11 non-null object
Unnamed: 10           11 non-null object
Unnamed: 11           11 non-null object
Unnamed: 12           11 non-null object
Unnamed: 13           11 non-null object
Unnamed: 14           11 non-null object
Unnamed: 15           11 non-null object
Unnamed: 16           11 non-null object
Unnamed: 17           11 non-null object
Unnamed: 18           11 non-null object
Unnamed: 19           11 non-null object
Unnamed: 20           11 non-null object
Unnamed: 21           11 non-null object
Unnamed: 22           11 non-null object
Unnamed: 23           11 non-null object
Unnamed: 24           11 non-null object
Unnamed: 25           11 non-null object
Unnamed: 26           11 non-null object
Unnamed: 27           11 non-null object
Unnamed: 28           11 non-null object
Unnamed: 29           11 non-null object
Unnamed: 30           11 non-null object
Unnamed: 31           11 non-null object
Unnamed: 32           11 non-null object
Unnamed: 33           11 non-null object
Unnamed: 34           11 non-null object
Unnamed: 35           11 non-null object
Unnamed: 36           11 non-null object
Unnamed: 37           11 non-null object
Unnamed: 38           11 non-null object
Unnamed: 39           11 non-null object
Unnamed: 40           11 non-null object
Unnamed: 41           11 non-null object
Unnamed: 42           11 non-null object
Unnamed: 43           11 non-null object
Unnamed: 44           11 non-null object
Unnamed: 45           11 non-null object
Unnamed: 46           11 non-null object
dtypes: int64(1), object(46)
memory usage: 21.0+ KB

In [3]:
df

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,JURISDICTION NAME,10005.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,COUNT PARTICIPANTS,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,COUNT FEMALE,4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,PERCENT FEMALE,0.404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,COUNT MALE,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,PERCENT MALE,0.396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,COUNT GENDER UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,PERCENT GENDER UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,COUNT GENDER TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,PERCENT GENDER TOTAL,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,COUNT PACIFIC ISLANDER,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,PERCENT PACIFIC ISLANDER,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,COUNT HISPANIC LATINO,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,PERCENT HISPANIC LATINO,0.105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,COUNT AMERICAN INDIAN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,PERCENT AMERICAN INDIAN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,COUNT ASIAN NON HISPANIC,3.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,PERCENT ASIAN NON HISPANIC,0.437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,COUNT WHITE NON HISPANIC,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,PERCENT WHITE NON HISPANIC,0.036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,COUNT BLACK NON HISPANIC,2.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23,PERCENT BLACK NON HISPANIC,0.181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,COUNT OTHER ETHNICITY,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,PERCENT OTHER ETHNICITY,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,COUNT ETHNICITY UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,PERCENT ETHNICITY UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,COUNT ETHNICITY TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,PERCENT ETHNICITY TOTAL,79.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30,COUNT PERMANENT RESIDENT ALIEN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,31,PERCENT PERMANENT RESIDENT ALIEN,0.061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,32,COUNT US CITIZEN,8.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,33,PERCENT US CITIZEN,0.739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,34,COUNT OTHER CITIZEN STATUS,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,35,PERCENT OTHER CITIZEN STATUS,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,36,COUNT CITIZEN STATUS UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,37,PERCENT CITIZEN STATUS UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,38,COUNT CITIZEN STATUS TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39,PERCENT CITIZEN STATUS TOTAL,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,40,COUNT RECEIVES PUBLIC ASSISTANCE,2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,41,PERCENT RECEIVES PUBLIC ASSISTANCE,0.151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,42,COUNT NRECEIVES PUBLIC ASSISTANCE,7.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,43,PERCENT NRECEIVES PUBLIC ASSISTANCE,0.649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,44,COUNT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,45,PERCENT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,46,COUNT PUBLIC ASSISTANCE TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
47,48,10001,44,22,0.5,22,0.5,0,0,44,...,44,100,20,0.45,24,0.55,0,0,44,100
48,49,10002,35,19,0.54,16,0.46,0,0,35,...,35,100,2,0.06,33,0.94,0,0,35,100
49,50,10003,1,1,1,0,0,0,0,1,...,1,100,0,0,1,1,0,0,1,100
50,51,10004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,52,10005,2,2,1,0,0,0,0,2,...,2,100,0,0,2,1,0,0,2,100
52,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0,6,1,0,0,6,100
53,54,10007,1,0,0,1,1,0,0,1,...,1,100,1,1,0,0,0,0,1,100
54,55,10009,2,0,0,2,1,0,0,2,...,2,100,0,0,2,1,0,0,2,100
55,56,10010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0,3,1,0,0,3,100

In [5]:
df1 = df.loc[2:46]
df1

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
2,3,COUNT PARTICIPANTS,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,COUNT FEMALE,4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,PERCENT FEMALE,0.404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,COUNT MALE,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,PERCENT MALE,0.396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,COUNT GENDER UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,PERCENT GENDER UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,COUNT GENDER TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,PERCENT GENDER TOTAL,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,COUNT PACIFIC ISLANDER,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,PERCENT PACIFIC ISLANDER,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,COUNT HISPANIC LATINO,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,PERCENT HISPANIC LATINO,0.105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,COUNT AMERICAN INDIAN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,PERCENT AMERICAN INDIAN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,COUNT ASIAN NON HISPANIC,3.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,PERCENT ASIAN NON HISPANIC,0.437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,COUNT WHITE NON HISPANIC,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,PERCENT WHITE NON HISPANIC,0.036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,COUNT BLACK NON HISPANIC,2.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23,PERCENT BLACK NON HISPANIC,0.181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,COUNT OTHER ETHNICITY,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,PERCENT OTHER ETHNICITY,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,COUNT ETHNICITY UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,PERCENT ETHNICITY UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,COUNT ETHNICITY TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,PERCENT ETHNICITY TOTAL,79.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30,COUNT PERMANENT RESIDENT ALIEN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,31,PERCENT PERMANENT RESIDENT ALIEN,0.061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,32,COUNT US CITIZEN,8.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,33,PERCENT US CITIZEN,0.739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,34,COUNT OTHER CITIZEN STATUS,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,35,PERCENT OTHER CITIZEN STATUS,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,36,COUNT CITIZEN STATUS UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,37,PERCENT CITIZEN STATUS UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,38,COUNT CITIZEN STATUS TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39,PERCENT CITIZEN STATUS TOTAL,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,40,COUNT RECEIVES PUBLIC ASSISTANCE,2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,41,PERCENT RECEIVES PUBLIC ASSISTANCE,0.151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,42,COUNT NRECEIVES PUBLIC ASSISTANCE,7.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,43,PERCENT NRECEIVES PUBLIC ASSISTANCE,0.649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,44,COUNT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,45,PERCENT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,46,COUNT PUBLIC ASSISTANCE TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL

In [ ]:
header = list

In [6]:
trycolumn = list(df.iloc[:,1])

In [58]:
trycolumn

[nan,
 0,
 10005.8,
 9.4,
 4.8,
 0.404,
 4.6,
 0.396,
 0,
 0,
 9.4,
 80,
 0,
 0,
 2,
 0.105,
 0,
 0,
 3.6,
 0.437,
 0.8,
 0.036,
 2.6,
 0.181,
 0.4,
 0.04,
 0,
 0,
 9.4,
 79.9,
 0.5,
 0.061,
 8.9,
 0.739,
 0,
 0,
 0,
 0,
 9.4,
 80,
 2.3,
 0.151,
 7.1,
 0.649,
 0,
 0,
 9.4,
 'COUNT PARTICIPANTS',
 44,
 35,
 1,
 0,
 2,
 6,
 1,
 2,
 0,
 3]

In [7]:
averages = trycolumn[2:47]

In [9]:
averages

[10005.8,
 9.4,
 4.8,
 0.404,
 4.6,
 0.396,
 0,
 0,
 9.4,
 80,
 0,
 0,
 2,
 0.105,
 0,
 0,
 3.6,
 0.437,
 0.8,
 0.036,
 2.6,
 0.181,
 0.4,
 0.04,
 0,
 0,
 9.4,
 79.9,
 0.5,
 0.061,
 8.9,
 0.739,
 0,
 0,
 0,
 0,
 9.4,
 80,
 2.3,
 0.151,
 7.1,
 0.649,
 0,
 0,
 9.4]

In [8]:
df2 = df.loc[48:57]

In [9]:
df2

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
48,49,10002,35,19,0.54,16,0.46,0,0,35,...,35,100,2,0.06,33,0.94,0,0,35,100
49,50,10003,1,1,1,0,0,0,0,1,...,1,100,0,0,1,1,0,0,1,100
50,51,10004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,52,10005,2,2,1,0,0,0,0,2,...,2,100,0,0,2,1,0,0,2,100
52,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0,6,1,0,0,6,100
53,54,10007,1,0,0,1,1,0,0,1,...,1,100,1,1,0,0,0,0,1,100
54,55,10009,2,0,0,2,1,0,0,2,...,2,100,0,0,2,1,0,0,2,100
55,56,10010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0,3,1,0,0,3,100

In [10]:
header = list(df.loc[47])

In [11]:
header

[48,
 '10001',
 '44',
 '22',
 '0.5',
 '22',
 '0.5',
 '0',
 '0',
 '44',
 '100',
 '0',
 '0',
 '16',
 '0.36',
 '0',
 '0',
 '3',
 '0.07',
 '1',
 '0.02',
 '21',
 '0.48',
 '3',
 '0.07',
 '0',
 '0',
 '44',
 '100',
 '2',
 '0.05',
 '42',
 '0.95',
 '0',
 '0',
 '0',
 '0',
 '44',
 '100',
 '20',
 '0.45',
 '24',
 '0.55',
 '0',
 '0',
 '44',
 '100']

In [14]:
df2.columns = header

In [15]:
df2

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
48,10001,44,22,0.5,22,0.5,0,0,44,100,...,44,100,20,0.45,24,0.55,0,0,44,100
49,10002,35,19,0.54,16,0.46,0,0,35,100,...,35,100,2,0.06,33,0.94,0,0,35,100
50,10003,1,1,1,0,0,0,0,1,100,...,1,100,0,0,1,1,0,0,1,100
51,10004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
52,10005,2,2,1,0,0,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
53,10006,6,2,0.33,4,0.67,0,0,6,100,...,6,100,0,0,6,1,0,0,6,100
54,10007,1,0,0,1,1,0,0,1,100,...,1,100,1,1,0,0,0,0,1,100
55,10009,2,0,0,2,1,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
56,10010,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57,10011,3,2,0.67,1,0.33,0,0,3,100,...,3,100,0,0,3,1,0,0,3,100

In [16]:
df2.index = range(1, (len(df2) + 1))

In [17]:
df2

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
1,10001,44,22,0.5,22,0.5,0,0,44,100,...,44,100,20,0.45,24,0.55,0,0,44,100
2,10002,35,19,0.54,16,0.46,0,0,35,100,...,35,100,2,0.06,33,0.94,0,0,35,100
3,10003,1,1,1,0,0,0,0,1,100,...,1,100,0,0,1,1,0,0,1,100
4,10004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,10005,2,2,1,0,0,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
6,10006,6,2,0.33,4,0.67,0,0,6,100,...,6,100,0,0,6,1,0,0,6,100
7,10007,1,0,0,1,1,0,0,1,100,...,1,100,1,1,0,0,0,0,1,100
8,10009,2,0,0,2,1,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
9,10010,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,10011,3,2,0.67,1,0.33,0,0,3,100,...,3,100,0,0,3,1,0,0,3,100

In [34]:
means = df2.mean()

In [35]:
means

JURISDICTION NAME                      10005.800
COUNT PARTICIPANTS                         9.400
COUNT FEMALE                               4.800
PERCENT FEMALE                             0.404
COUNT MALE                                 4.600
PERCENT MALE                               0.396
COUNT GENDER UNKNOWN                       0.000
PERCENT GENDER UNKNOWN                     0.000
COUNT GENDER TOTAL                         9.400
PERCENT GENDER TOTAL                      80.000
COUNT PACIFIC ISLANDER                     0.000
PERCENT PACIFIC ISLANDER                   0.000
COUNT HISPANIC LATINO                      2.000
PERCENT HISPANIC LATINO                    0.105
COUNT AMERICAN INDIAN                      0.000
PERCENT AMERICAN INDIAN                    0.000
COUNT ASIAN NON HISPANIC                   3.600
PERCENT ASIAN NON HISPANIC                 0.437
COUNT WHITE NON HISPANIC                   0.800
PERCENT WHITE NON HISPANIC                 0.036
COUNT BLACK NON HISPANIC                   2.600
PERCENT BLACK NON HISPANIC                 0.181
COUNT OTHER ETHNICITY                      0.400
PERCENT OTHER ETHNICITY                    0.040
COUNT ETHNICITY UNKNOWN                    0.000
PERCENT ETHNICITY UNKNOWN                  0.000
COUNT ETHNICITY TOTAL                      9.400
PERCENT ETHNICITY TOTAL                   79.900
COUNT PERMANENT RESIDENT ALIEN             0.500
PERCENT PERMANENT RESIDENT ALIEN           0.061
COUNT US CITIZEN                           8.900
PERCENT US CITIZEN                         0.739
COUNT OTHER CITIZEN STATUS                 0.000
PERCENT OTHER CITIZEN STATUS               0.000
COUNT CITIZEN STATUS UNKNOWN               0.000
PERCENT CITIZEN STATUS UNKNOWN             0.000
COUNT CITIZEN STATUS TOTAL                 9.400
PERCENT CITIZEN STATUS TOTAL              80.000
COUNT RECEIVES PUBLIC ASSISTANCE           2.300
PERCENT RECEIVES PUBLIC ASSISTANCE         0.151
COUNT NRECEIVES PUBLIC ASSISTANCE          7.100
PERCENT NRECEIVES PUBLIC ASSISTANCE        0.649
COUNT PUBLIC ASSISTANCE UNKNOWN            0.000
PERCENT PUBLIC ASSISTANCE UNKNOWN          0.000
COUNT PUBLIC ASSISTANCE TOTAL              9.400
PERCENT PUBLIC ASSISTANCE TOTAL           80.000
dtype: float64

In [39]:
type(means)

pandas.core.series.Series

In [40]:
new_df = df2.append(means, ignore_index = True)

In [41]:
new_df

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
0,10001,44,22,0.5,22,0.5,0,0,44,100,...,44,100,20,0.45,24,0.55,0,0,44,100
1,10002,35,19,0.54,16,0.46,0,0,35,100,...,35,100,2,0.06,33,0.94,0,0,35,100
2,10003,1,1,1,0,0,0,0,1,100,...,1,100,0,0,1,1,0,0,1,100
3,10004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,10005,2,2,1,0,0,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
5,10006,6,2,0.33,4,0.67,0,0,6,100,...,6,100,0,0,6,1,0,0,6,100
6,10007,1,0,0,1,1,0,0,1,100,...,1,100,1,1,0,0,0,0,1,100
7,10009,2,0,0,2,1,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
8,10010,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,10011,3,2,0.67,1,0.33,0,0,3,100,...,3,100,0,0,3,1,0,0,3,100
10,10005.8,9.4,4.8,0.404,4.6,0.396,0,0,9.4,80,...,9.4,80,2.3,0.151,7.1,0.649,0,0,9.4,80

In [44]:
new_df.index = range(1, (len(new_df) + 1))

In [45]:
new_df.index

RangeIndex(start=1, stop=12, step=1)

In [46]:
new_df

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
1,10001,44,22,0.5,22,0.5,0,0,44,100,...,44,100,20,0.45,24,0.55,0,0,44,100
2,10002,35,19,0.54,16,0.46,0,0,35,100,...,35,100,2,0.06,33,0.94,0,0,35,100
3,10003,1,1,1,0,0,0,0,1,100,...,1,100,0,0,1,1,0,0,1,100
4,10004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,10005,2,2,1,0,0,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
6,10006,6,2,0.33,4,0.67,0,0,6,100,...,6,100,0,0,6,1,0,0,6,100
7,10007,1,0,0,1,1,0,0,1,100,...,1,100,1,1,0,0,0,0,1,100
8,10009,2,0,0,2,1,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
9,10010,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,10011,3,2,0.67,1,0.33,0,0,3,100,...,3,100,0,0,3,1,0,0,3,100
11,10005.8,9.4,4.8,0.404,4.6,0.396,0,0,9.4,80,...,9.4,80,2.3,0.151,7.1,0.649,0,0,9.4,80

In [53]:
new_df.rename(index = {11:'Average'}, inplace = True)

In [54]:
new_df

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
1,10001,44,22,0.5,22,0.5,0,0,44,100,...,44,100,20,0.45,24,0.55,0,0,44,100
2,10002,35,19,0.54,16,0.46,0,0,35,100,...,35,100,2,0.06,33,0.94,0,0,35,100
3,10003,1,1,1,0,0,0,0,1,100,...,1,100,0,0,1,1,0,0,1,100
4,10004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,10005,2,2,1,0,0,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
6,10006,6,2,0.33,4,0.67,0,0,6,100,...,6,100,0,0,6,1,0,0,6,100
7,10007,1,0,0,1,1,0,0,1,100,...,1,100,1,1,0,0,0,0,1,100
8,10009,2,0,0,2,1,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
9,10010,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,10011,3,2,0.67,1,0.33,0,0,3,100,...,3,100,0,0,3,1,0,0,3,100
Average,10005.8,9.4,4.8,0.404,4.6,0.396,0,0,9.4,80,...,9.4,80,2.3,0.151,7.1,0.649,0,0,9.4,80

In [55]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 1 to Average
Data columns (total 46 columns):
JURISDICTION NAME                      11 non-null object
COUNT PARTICIPANTS                     11 non-null object
COUNT FEMALE                           11 non-null object
PERCENT FEMALE                         11 non-null object
COUNT MALE                             11 non-null object
PERCENT MALE                           11 non-null object
COUNT GENDER UNKNOWN                   11 non-null object
PERCENT GENDER UNKNOWN                 11 non-null object
COUNT GENDER TOTAL                     11 non-null object
PERCENT GENDER TOTAL                   11 non-null object
COUNT PACIFIC ISLANDER                 11 non-null object
PERCENT PACIFIC ISLANDER               11 non-null object
COUNT HISPANIC LATINO                  11 non-null object
PERCENT HISPANIC LATINO                11 non-null object
COUNT AMERICAN INDIAN                  11 non-null object
PERCENT AMERICAN INDIAN                11 non-null object
COUNT ASIAN NON HISPANIC               11 non-null object
PERCENT ASIAN NON HISPANIC             11 non-null object
COUNT WHITE NON HISPANIC               11 non-null object
PERCENT WHITE NON HISPANIC             11 non-null object
COUNT BLACK NON HISPANIC               11 non-null object
PERCENT BLACK NON HISPANIC             11 non-null object
COUNT OTHER ETHNICITY                  11 non-null object
PERCENT OTHER ETHNICITY                11 non-null object
COUNT ETHNICITY UNKNOWN                11 non-null object
PERCENT ETHNICITY UNKNOWN              11 non-null object
COUNT ETHNICITY TOTAL                  11 non-null object
PERCENT ETHNICITY TOTAL                11 non-null object
COUNT PERMANENT RESIDENT ALIEN         11 non-null object
PERCENT PERMANENT RESIDENT ALIEN       11 non-null object
COUNT US CITIZEN                       11 non-null object
PERCENT US CITIZEN                     11 non-null object
COUNT OTHER CITIZEN STATUS             11 non-null object
PERCENT OTHER CITIZEN STATUS           11 non-null object
COUNT CITIZEN STATUS UNKNOWN           11 non-null object
PERCENT CITIZEN STATUS UNKNOWN         11 non-null object
COUNT CITIZEN STATUS TOTAL             11 non-null object
PERCENT CITIZEN STATUS TOTAL           11 non-null object
COUNT RECEIVES PUBLIC ASSISTANCE       11 non-null object
PERCENT RECEIVES PUBLIC ASSISTANCE     11 non-null object
COUNT NRECEIVES PUBLIC ASSISTANCE      11 non-null object
PERCENT NRECEIVES PUBLIC ASSISTANCE    11 non-null object
COUNT PUBLIC ASSISTANCE UNKNOWN        11 non-null object
PERCENT PUBLIC ASSISTANCE UNKNOWN      11 non-null object
COUNT PUBLIC ASSISTANCE TOTAL          11 non-null object
PERCENT PUBLIC ASSISTANCE TOTAL        11 non-null object
dtypes: object(46)
memory usage: 4.0+ KB

## Level Up (Optional) - Loading Corrupt CSV files

Occasionally, you encountered some really ill formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is supposed to use quotes to differentiate between the commas denoting fields and commas within those fields themselves. For example, we could have a table like this:  

ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restaurant was pretty good, we had a great time.,98765

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restaurant was pretty good, we had a great time.","98765"

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled Yelp_Reviews_corrupt.csv. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [ ]:
#Hint: here's a useful programming pattern to use.
try:
    #do something
except Exception as e:
    #handle your exception e

In [ ]:
#Your code here

## Summary

Congratulations, you now practiced your pandas-importing skills!